---
name: "Simsong"
default_settings: &default_settings
  color: none
  speed: 100
  cars_number: 100
  station_fuel_reserve: 3000
  station_closing_tick: 300
  cars_delay_interval_range: !ruby/range 2..5
  cars_level_range: !ruby/range 1..1
  cars_volume_range: !ruby/range 35..35
  pumps_number_range: !ruby/range 36..36
  pumps_speed_range: !ruby/range 3..3

scenarios:
  alpha:
    simulations:
    - name: Sim 0
      <<: *default_settings

  beta:
    simulations:
    - name: Sim 1
      color: red
      <<: *default_settings

    - name: Sim 2
      color: yellow
      <<: *default_settings

  gamma:
    simulations:
    - name: Sim 3
      <<: *default_settings
      pumps_number_range: !ruby/range 2..2
      pumps_speed_range: !ruby/range 1..1

    - name: Sim 4
      <<: *default_settings
      pumps_number_range: !ruby/range 3..3
      pumps_speed_range: !ruby/range 2..2

    - name: Sim 5
      <<: *default_settings
      pumps_number_range: !ruby/range 4..4
      pumps_speed_range: !ruby/range 3..3

    # - name: Sim 6
    #   <<: *default_settings

    # - name: Sim 7
    #   <<: *default_settings

    # - name: Sim 8
    #   <<: *default_settings

    # - name: Sim 9
    #   <<: *default_settings

    # - name: Sim 10
    #   <<: *default_settings

    # - name: Sim 11
    #   <<: *default_settings

    # - name: Sim 12
    #   <<: *default_settings

    # - name: Sim 13
    #   <<: *default_settings

    # - name: Sim 14
    #   <<: *default_settings